# Generated by Django 2.2 on 2019-06-18 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_pet_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='password',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
